# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0fGetStartRequest\x12\x0c\n\x04keys\x18\x01 \x03(\x0c\"2\n\x06Handle\x12\x0b\n\x03key\x18\x01 \x02(\x0c\x12\x0e\n\x06offset\x18\x02 \x02(\x04\x12\x0b\n\x03len\x18\x03 \x02(\x04\":\n\rGetStartReply\x12\x0f\n\x07\x62\x61tchID\x18\x01 \x02(\x04\x12\x18\n\x07handles\x18\x02 \x03(\x0b\x32\x07.Handle\"1\n\rGetEndRequest\x12\x0f\n\x07\x62\x61tchID\x18\x01 \x02(\x04\x12\x0f\n\x07revoked\x18\x02 \x02(\x08\"-\n\x0fPutStartRequest\x12\x0c\n\x04keys\x18\x01 \x03(\x0c\x12\x0c\n\x04lens\x18\x02 \x03(\x04\"A\n\rPutStartReply\x12\x0f\n\x07\x62\x61tchID\x18\x01 \x02(\x04\x12\x0f\n\x07offsets\x18\x02 \x03(\x04\x12\x0e\n\x06\x65xists\x18\x03 \x03(\x08\" \n\rPutEndRequest\x12\x0f\n\x07\x62\x61tchID\x18\x01 \x02(\x04\x32\xcf\x01\n\x05\x43\x61\x63he\x12.\n\x08GetStart\x12\x10.GetStartRequest\x1a\x0e.GetStartReply\"\x00\x12\x32\n\x06GetEnd\x12\x0e.GetEndRequest\x1a\x16.google.protobuf.Empty\"\x00\x12.\n\x08PutStart\x12\x10.PutStartRequest\x1a\x0e.PutStartReply\"\x00\x12\x32\n\x06PutEnd\x12\x0e.PutEndRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x17Z\x15\x63xl_manager/rpc/proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025cxl_manager/rpc/proto'
  _globals['_GETSTARTREQUEST']._serialized_start=44
  _globals['_GETSTARTREQUEST']._serialized_end=75
  _globals['_HANDLE']._serialized_start=77
  _globals['_HANDLE']._serialized_end=127
  _globals['_GETSTARTREPLY']._serialized_start=129
  _globals['_GETSTARTREPLY']._serialized_end=187
  _globals['_GETENDREQUEST']._serialized_start=189
  _globals['_GETENDREQUEST']._serialized_end=238
  _globals['_PUTSTARTREQUEST']._serialized_start=240
  _globals['_PUTSTARTREQUEST']._serialized_end=285
  _globals['_PUTSTARTREPLY']._serialized_start=287
  _globals['_PUTSTARTREPLY']._serialized_end=352
  _globals['_PUTENDREQUEST']._serialized_start=354
  _globals['_PUTENDREQUEST']._serialized_end=386
  _globals['_CACHE']._serialized_start=389
  _globals['_CACHE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
